dist: xenial
language: python
sudo: false

python:
  - 3.6
  - 3.7
  - 3.8

env:

  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=2.2
  - DJANGO=3.0


install:
  - pip install tox-travis
  - pip install "coverage<=4.0" codecov

script:
  - tox -e "py${TRAVIS_PYTHON_VERSION//.}-d${DJANGO//.}"

after_success:
  - coverage combine
  - codecov
